### ISSUE TITLE
Mapping for enum property

### ISSUE THREAD

**Issue by anantakrishna** [dtretyakov/WindowsAzure#43]
Is it possible to map enum property?
Now I'm getting the following error:
```
Invalid entity member type: 'MyEnumType'.
```

**Comment by dtretyakov** [comment]
Hello, we can implement enumeration type members mapping. It would be great if you can send a PR with a broken unit test to demonstrate this case.

**Comment by gblmarquez** [comment]
Fixed on PR #51
