### ISSUE TITLE
.NET Core (.NET Standard) Support

### ISSUE THREAD

**Issue by Deilan** [dtretyakov/WindowsAzure#53]
Since the latest versions of [WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage/) added a support of .NET Core (.NET Standard), it is time to do the same here. :P

**Comment by dtretyakov** [comment]
You can try to download beta package build:
https://www.nuget.org/packages/WindowsAzure.StorageExtensions/1.1.0-beta1

**Comment by Deilan** [comment]
@dtretyakov Thanks! But what about going into production? Almost a half year passed since the beta package was released..

**Comment by ognyandim** [comment]
We are using it happily in production for at least one year :)

**Comment by ognyandim** [comment]
We are using this (.NET Standard) in multi instance web app in production for more than an year - works fine!

**Comment by Deilan** [comment]
@ognyandim Thanks for sharing your experience! Prerelease state of the package could be a concern and I suppose there are reasons the package is in that state, which is up to the package provisioner @dtretyakov.

**Comment by dtretyakov** [comment]
@Deilan, it was in the prerelease state mostly due to unstability of MSFT tooling for .NET Core.
After project upgrade to the new csproj I'll publish a new stable version of the package.

**Comment by Rzpeg** [comment]
Hey, when are you planning to publish the release version of .net standard package ?
